services:
  trakt-sync:
    build:
      context: .
      dockerfile: dockerfile
    container_name: trakt-sync
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./config:/config # Mount config outside container
    environment:
      - CONFIG_PATH=/config # Path used inside container