### Base URL
@baseUrl = http://localhost:3000

### Get Config
GET {{baseUrl}}/config
Content-Type: application/json

### Patch Config
PATCH {{baseUrl}}/config
Content-Type: application/json

{
  "trakt": {
    "client_id": "eb4ede9a384157e9aa60aad8c72c36c0485215659c82ad7b1fe965359a55caf4",
    "client_secret": "test",
    "access_token": "test",
    "code": "test",
    "redirect_url": "urn:ietf:wg:oauth:2.0:oob"
  },
  "emby": {
    "api_key": "b039ba2b065e4ba1bca2307cce593478",
    "base_url": "http://192.168.1.13:8096"
  },
  "cronjob": "* * * * *"
}
