### Base URL
@baseUrl = http://localhost:5007

### Get config
GET {{baseUrl}}/api/config
Content-Type: application/json

### Update config
POST {{baseUrl}}/api/config
Content-Type: application/json

{
  "Trakt": {
    "BaseUrl": "https://api.trakt.tv",
    "ApiVersion": "2",
    "RedirectUrl": "urn:ietf:wg:oauth:2.0:oob",
    "UserName": "lfmachadodasilva",
    "ClientId": "CLIENT_ID_HERE",
    "ClientSecret": "CLIENT_SECRET_HERE",
    "AccessToken": "ACCESS_TOKEN_HERE",
    "RefreshToken": "REFRESH_TOKEN_HERE",
    "TokenType": "Bearer"
  },
  "Emby": {
    "BaseUrl": "http://192.168.1.13:8096",
    "UserId": "USER_ID_HERE",
    "ApiKey": "API_KEY_HERE"
  },
  "Plex": null
}