### Base URL
@baseUrl = http://localhost:4000

### Get code
GET {{baseUrl}}/trakt/code
Content-Type: application/json

### Authenticate with code
POST {{baseUrl}}/trakt/auth
Content-Type: application/json

{
  "code": "d87d9d27"
}

### Refresh access token
POST {{baseUrl}}/trakt/auth/refresh
Content-Type: application/json

{}