name: trakt-sync build

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: lfmachadodasilva/trakt-sync

      - name: Sanitize tag name
        id: sanitize
        run: echo "TAG=${GITHUB_REF_NAME//\//-}" >> $GITHUB_ENV
        
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          cache-from: type=registry,ref=lfmachadodasilva/trakt-sync:latest
          cache-to: type=inline
          push: ${{ startsWith(github.ref, 'refs/tags/v') }}
          tags: |
            lfmachadodasilva/trakt-sync:latest
            lfmachadodasilva/trakt-sync:${{ env.TAG }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation (only for tags)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: index.docker.io/lfmachadodasilva/trakt-sync
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true